version: '3.4'

services:
  smartexamsrails:
    image: smartexamsrails
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
     image: redis:5.0.7
     ports:
       - '6379:6379'
     volumes:
       - ./var/lib/redis/data