version: "3.9"

services:
  # webserver:
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #   links:
  #     - web:web
  # end of ningx web server

  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: password

      # end of db

  redis:
    image: 'redis:4.0-alpine'
    sysctls:
      net.core.somaxconn: 2048
    command: redis-server
    # command: redis-server --requirepass 'Redis@password@SE'
    volumes:
      - redis-data:/data
  # end of redis

  web:
    tty: true
    stdin_open: true
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
  # enf of web rails application

  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bash -c "bundle exec sidekiq"
    env_file:
      - '.env'
    # By default Docker Compose will look for an .env file in the same directory as your docker-compose.yml file.

    # docker-compose --env-file ./config/.env.dev up 

volumes:
  postgres-data:
  redis-data: