default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  # database: smart-exams-bhosale
  database: smart-exams-1

test:
  <<: *default
  database: smart-exams-test
