default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  ## DOCKER
  host: localhost
  username: postgres
  password: password

development:
  <<: *default
  database: smart-exams-bhosale
  # database: smart-exams-1

test:
  <<: *default
  database: smart-exams-test
